### PR TITLE
typo, missing `@` sign

### PR DESCRIPTION
**Pull request by wires**
Missing `@` sign, might be confusing to users.

### CODE REVIEW

**Comment by aseemk** [comment]
Thanks!

**Comment by aseemk** [comment]
If it's cool, I'll rebase/amend the readme commit to fix this, rather than have it as a separate commit. Rest assured your eagle eyes are appreciated. =)

**Comment by aseemk** [comment]
Fixed in the v2 branch.

**Comment by wires** [comment]
ok

**Pull request closed without merging**
