### PR TITLE
Proposed README changes

### PR DESCRIPTION
**Pull request by cheerfulstoic**
Includes:

 * An intro to Neo4j
 * Adding username/password to example to show usage of auth
 * Added "Getting Help" section to replace "Feedback" section and moved it up
 * Support matrices to show what features are supported in v1 and v2

Question: Do you support transactions or HA mode?  It didn't seem so from your docs, but I wanted to check.

You also might want to think about having a `CONTRIBUTING.md` file:

https://github.com/blog/1184-contributing-guidelines

### CODE REVIEW

**Comment by aseemk** [comment]
Sorry for the delay, @cheerfulstoic, but this is great stuff!

As I think you've seen, node-neo4j v2 is in RC mode in pull #145. It's almost done; I just need to finish the "last mile" (which is mainly docs), and this is helpful. =)

> Question: Do you support transactions or HA mode?

Transactions: yep.

https://github.com/thingdom/node-neo4j/blob/v2/API_v2.md#transactions
https://github.com/thingdom/node-neo4j/blob/v2/test-new/transactions._coffee

HA mode: curious if you can clarify. We run HA mode in production at @FiftyThree, using this driver, so yes we support it, but we distribute load via our own HAProxy load balancer, so this driver doesn't need to know or do anything special for that. (Similar to how Heroku routers load balance web requests, but web browsers don't need to know anything about that.)

We *do* also split reads and writes, and we distinguish those via a custom header (`X-Request-Consistency`) which we look at in our HAProxy configuration. This driver supports that use case via custom HTTP headers.

**Comment by cheerfulstoic** [comment]
That's a good point.  In the neo4j ruby gem we support HA a bit more directly by determining what session/address to use based on wether it is read or write.  We've had a bit of discussion around this and I'm actually curious how you determine the header.  With a model you can obviously tell what queries are reads and writes, but what about raw cypher queries?

I'm all for saying in the HA support line something like "indirectly via HTTP headers" with maybe a link to a page (GH wiki?) explaining what that means.

**Comment by aseemk** [comment]
Sorry for the delay here @cheerfulstoic! I'm going to go ahead and merge this as-is for now, but I'm reworking the docs for v2, so your feedback there will be welcome when that's done. Stay tuned.

> I'm actually curious how you determine the header. With a model you can obviously tell what queries are reads and writes, but what about raw cypher queries?

It's indeed not done by this driver — it's done at the application level. We do it based on the REST API method (e.g. GET/HEAD vs. PUT/POST/PATCH/DELETE).

> I'm all for saying in the HA support line something like "indirectly via HTTP headers" with maybe a link to a page (GH wiki?) explaining what that means.

Yes, this sounds reasonable. But I'm curious how else (more "directly") a driver could support HA if it's truly just a *driver* (wrapper around the REST API) and not an OGM or query builder?

**Comment by cheerfulstoic** [comment]
Yes, I think my idea of what a driver should do is probably affected by my experience with the Ruby gem which sort of mixes the concepts.  If it's just a driver then it probably calls for some more manual control.

Glad that the PR was helpful!

**Pull request merged**
